## Copyright 2020 Paingha Joe Alagoa. All rights reserved.
## Use of this source code is governed by a BSD-style
## license that can be found in the LICENSE file.

version: "3.7"
services:

  postgres:
    container_name: postgres-container
    image: postgres:alpine
    env_file: example.env
    environment:
      POSTGRES_DB: ${ENV_DEV_DB_USER}
      POSTGRES_USER: ${ENV_DEV_DB_USER}
      POSTGRES_PASSWORD: ${ENV_DEV_DB_PASS}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: on-failure
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file: example.env
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    restart: on-failure

  server:
    container_name: grpc-church-api-1
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      args:
        service: server
    restart: on-failure
    labels:
      NAME: "server"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    env_file: example.env
    environment:
      ENV_PROD_DB_HOST: ${ENV_PROD_DB_HOST}
      ENV_PROD_DB_PORT: ${ENV_PROD_DB_PORT}
      ENV_PROD_DB_USER: ${ENV_PROD_DB_USER}
      ENV_PROD_DB_PASS: ${ENV_PROD_DB_PASS}
      ENV_PROD_DB_DATABASE: ${ENV_PROD_DB_DATABASE}
      ENV_PROD_DB_SSL: ${ENV_PROD_DB_SSL}
      ENV_DEV_DB_HOST: ${ENV_DEV_DB_HOST}
      ENV_DEV_DB_PORT: ${ENV_DEV_DB_PORT}
      ENV_DEV_DB_USER: ${ENV_DEV_DB_USER}
      ENV_DEV_DB_PASS: ${ENV_DEV_DB_PASS}
      ENV_DEV_DB_DATABASE: ${ENV_DEV_DB_DATABASE}
      ENV_DEV_DB_SSL : ${ENV_DEV_DB_SSL}
      DATABASE_DEBUG_MODE: "true"
      JWT_SECRET: ${JWT_SECRET}
      ENV_BASE_URL: ${ENV_BASE_URL}
    depends_on:
      - postgres
      - envoy

  envoy:
    build: ./envoy
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"

  email:
    container_name: grpc-church-email-1
    build:
      context: ./
      dockerfile: ./email/Dockerfile
      args:
        service: email
    restart: on-failure
    labels:
      NAME: "email"
    expose:
      - "9001"
    ports:
      - "9001:9001"
    env_file: example.env
    environment:
      ENV_EMAIL_SENDER_NAME: ${ENV_EMAIL_SENDER_NAME}
      ENV_SENDER_EMAIL: ${ENV_SENDER_EMAIL}
      ENV_SENDGRID_API_KEY: ${ENV_SENDGRID_API_KEY}

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: